### ISSUE TITLE
Fire Emblem 776 Editor Not Working.

### ISSUE THREAD

**Issue by gaonnuris** [laqieer/nightmare#5]
FIREM EMBLEM 776 J
MD5 : c3fd1cad754256d7a013864d917f47fa
FIREM EMBLEM 776 J REB 0~1
MD5 :
(REV0): 26be9c87aac0cb3d3af5dffb4e6aa059
(REV1): b128f6cbbd323cdcd34a5b06003e1135

Edit is not working.
Please add.

**Comment by laqieer** [comment]
It works on SMC format instead of SFC format.
# Reason
SNES ROM has 2 formats:
- SMC: with ROM header
- SFC: without ROM header

The size of ROM header affects offsets for editing.
# Solution
2 alternative solutions:
- Convert SFC format to SMC format using a converter like [smc2sfc2](https://github.com/mwmccarthy/smc2sfc2)
-  Add an empty ROM header to fix offset calculation using a SNES ROM tool like [NSRT](https://www.romhacking.net/utilities/400/)
# Reference
https://feuniverse.us/t/is-there-a-good-tutorial-for-how-to-use-nightmare-modules-with-fe4/14963/4
